mod agent;
mod channels;
mod chunker;
mod config;
mod containers;
mod db;
mod gateway;
mod memory;
mod metrics;
mod oauth;
mod process_manager;
mod scheduler;
mod secrets;
mod mcp;
mod skills;
mod tasks;
mod tools;

use anyhow::Result;
use std::collections::HashMap;
use std::sync::Arc;
use tracing_subscriber::{layer::SubscriberExt, util::SubscriberInitExt, EnvFilter};

/// Load .env file from binary's directory or current working directory.
/// In production (systemd), env vars come from `EnvironmentFile`.
fn load_env() {
    let mut env_path = std::path::PathBuf::from(".env");

    // Try from binary's directory first (most reliable for production)
    if let Ok(exe_path) = std::env::current_exe()
        && let Some(dir) = exe_path.parent() {
            let p = dir.join(".env");
            if p.exists() {
                env_path = p;
            }
        }

    // Auto-generate .env on first run (only HYDECLAW_AUTH_TOKEN and HYDECLAW_MASTER_KEY)
    if !env_path.exists() {
        let mut auth_bytes = [0u8; 32];
        let mut key_bytes = [0u8; 32];
        rand::RngCore::fill_bytes(&mut rand::rng(), &mut auth_bytes);
        rand::RngCore::fill_bytes(&mut rand::rng(), &mut key_bytes);
        let content = format!(
            "# Auto-generated by hydeclaw-core on first run\nHYDECLAW_AUTH_TOKEN={}\nHYDECLAW_MASTER_KEY={}\n",
            hex::encode(auth_bytes),
            hex::encode(key_bytes),
        );
        if std::fs::write(&env_path, &content).is_ok() {
            eprintln!("[dotenv] created .env with generated tokens: {}", env_path.display());
        }
    }

    if env_path.exists() {
        if dotenv::from_path(&env_path).is_ok() {
            eprintln!("[dotenv] loaded .env from: {}", env_path.display());
        }
    } else {
        eprintln!("[dotenv] .env not found, using environment variables");
    }
}

/// Tracing layer that broadcasts log entries as JSON to WebSocket clients.
struct BroadcastLogLayer {
    tx: tokio::sync::broadcast::Sender<String>,
}

impl<S: tracing::Subscriber> tracing_subscriber::Layer<S> for BroadcastLogLayer {
    fn on_event(&self, event: &tracing::Event<'_>, _ctx: tracing_subscriber::layer::Context<'_, S>) {
        // Skip all work when no UI clients are subscribed
        if self.tx.receiver_count() == 0 { return; }

        use tracing_subscriber::field::Visit;

        struct Visitor {
            message: String,
        }
        impl Visit for Visitor {
            fn record_debug(&mut self, field: &tracing::field::Field, value: &dyn std::fmt::Debug) {
                if field.name() == "message" {
                    self.message = format!("{value:?}");
                }
            }
        }

        let mut visitor = Visitor { message: String::new() };
        event.record(&mut visitor);

        let level = match *event.metadata().level() {
            tracing::Level::ERROR => "ERROR",
            tracing::Level::WARN => "WARN",
            tracing::Level::INFO => "INFO",
            tracing::Level::DEBUG => "DEBUG",
            tracing::Level::TRACE => "DEBUG",
        };

        let json = serde_json::json!({
            "type": "log",
            "level": level,
            "target": event.metadata().target(),
            "message": visitor.message,
            "timestamp": chrono::Utc::now().to_rfc3339(),
        });

        // Best-effort send — drop if no subscribers
        self.tx.send(json.to_string()).ok();
    }
}

/// Initialize tracing subscriber with optional OTEL layer.
fn init_tracing(log_tx: tokio::sync::broadcast::Sender<String>, cfg: &config::AppConfig) {
    let env_filter = EnvFilter::try_from_default_env().unwrap_or_else(|_| "hydeclaw_core=info".into());
    let fmt_layer = tracing_subscriber::fmt::layer();
    let broadcast_layer = BroadcastLogLayer { tx: log_tx };

    #[cfg(feature = "otel")]
    {
        use opentelemetry_otlp::WithExportConfig;

        if cfg.otel.enabled {
            let endpoint = std::env::var("OTEL_EXPORTER_OTLP_ENDPOINT")
                .unwrap_or_else(|_| "http://localhost:4317".to_string());
            eprintln!("[otel] exporting traces to {endpoint} as {:?}", cfg.otel.service_name);

            if let Ok(exporter) = opentelemetry_otlp::SpanExporter::builder()
                .with_tonic()
                .with_endpoint(&endpoint)
                .build()
            {
                let provider = opentelemetry_sdk::trace::TracerProvider::builder()
                    .with_simple_exporter(exporter)
                    .with_resource(opentelemetry_sdk::Resource::new([
                        opentelemetry::KeyValue::new("service.name", cfg.otel.service_name.clone()),
                    ]))
                    .build();
                opentelemetry::global::set_tracer_provider(provider.clone());
                let tracer = opentelemetry::trace::TracerProvider::tracer(&provider, "hydeclaw");
                let otel_layer = tracing_opentelemetry::layer().with_tracer(tracer);

                tracing_subscriber::registry()
                    .with(env_filter)
                    .with(fmt_layer)
                    .with(broadcast_layer)
                    .with(otel_layer)
                    .init();
                return;
            }
            eprintln!("[otel] failed to create exporter, falling back to non-OTEL tracing");
        }
    }

    #[cfg(not(feature = "otel"))]
    let _ = &cfg.otel; // suppress unused warning

    tracing_subscriber::registry()
        .with(env_filter)
        .with(fmt_layer)
        .with(broadcast_layer)
        .init();
}

#[tokio::main(worker_threads = 4)]
async fn main() -> Result<()> {
    // Load .env file (no-op if not found - env vars may come from systemd EnvironmentFile)
    load_env();

    // Load config BEFORE tracing init (OTEL layer depends on config)
    let cfg = config::AppConfig::load("config/hydeclaw.toml")?;

    // Broadcast channel for real-time log streaming (created before tracing init)
    let (log_tx, _) = tokio::sync::broadcast::channel::<String>(256);

    // Structured logging with broadcast layer for UI + optional OTEL
    init_tracing(log_tx.clone(), &cfg);

    tracing::info!(listen = %cfg.gateway.listen, "HydeClaw Core starting...");

    // Auto-install systemd units for watchdog and memory-worker
    setup_systemd_units();

    // Config hot-reload watcher
    let shared_config = std::sync::Arc::new(tokio::sync::RwLock::new(cfg.clone()));
    let config_api_write_flag = std::sync::Arc::new(std::sync::atomic::AtomicBool::new(false));
    config::spawn_config_watcher("config/hydeclaw.toml".to_string(), shared_config.clone(), config_api_write_flag.clone());

    // Database pool — DATABASE_URL env var overrides hydeclaw.toml value
    let db_url = std::env::var("DATABASE_URL").unwrap_or_else(|_| cfg.database.url.clone());
    let db_pool = db::create_pool(&db_url).await?;
    tracing::info!("database connected, running migrations...");
    sqlx::migrate::Migrator::new(std::path::Path::new("migrations"))
        .await?
        .run(&db_pool)
        .await?;
    tracing::info!("migrations complete");

    // Startup cleanup: repair sessions interrupted by previous crash (batched)
    cleanup_interrupted_sessions(&db_pool).await;

    // Secrets vault
    let master_key_hex = get_master_key();
    let secrets_manager = secrets::SecretsManager::new(&master_key_hex, db_pool.clone())?;
    let secrets_count = secrets_manager.load_all().await?;

    // One-time migration: move channel credentials from JSONB to encrypted vault.
    // Idempotent — safe to run every startup.
    gateway::migrate_credentials_to_vault(&db_pool, &secrets_manager).await;
    // One-time migration: copy provider keys from legacy vault patterns into unified PROVIDER_CREDENTIALS.
    gateway::migrate_provider_keys_to_vault(&db_pool, &secrets_manager).await;
    // One-time migration: move OAuth tokens/credentials from old per-agent format to per-account vault.
    if let Err(e) = crate::oauth::migrate_oauth_vault(&db_pool, &secrets_manager).await {
        tracing::error!(error = %e, "OAuth vault migration failed — old tokens may not be available");
    }

    // No hardcoded secrets — user creates all secrets via UI.
    // Channel-specific secrets (bot tokens) are auto-seeded when agents are created.
    // HYDECLAW_AUTH_TOKEN and HYDECLAW_MASTER_KEY stay in .env only (bootstrap).

    let secrets_manager = Arc::new(secrets_manager);
    tracing::info!(count = secrets_count, "secrets vault loaded");

    // Memory store (embedding via toolgate proxy)
    let toolgate_url = cfg.toolgate_url.clone().unwrap_or_else(|| "http://localhost:9011".to_string());
    let effective_toolgate_url = if cfg.memory.enabled { &toolgate_url } else { "" };
    let embedder: Arc<dyn memory::EmbeddingService> = Arc::new(memory::ToolgateEmbedder::new(
        db_pool.clone(),
        effective_toolgate_url,
        cfg.memory.embed_dim.unwrap_or(0),
        cfg.memory.embed_dimensions.unwrap_or(0),
    ));
    let fts_lang = cfg.memory.fts_language.clone().unwrap_or_else(|| "simple".to_string());
    let memory_store = Arc::new(memory::MemoryStore::new(db_pool.clone(), embedder.clone(), fts_lang));
    if embedder.is_available() {
        tracing::info!("embedding configured — will initialize on first memory operation");
        // Watch workspace files for auto-reindexing
        memory::spawn_workspace_watcher(
            config::WORKSPACE_DIR.to_string(),
            memory_store.clone(),
            tokio::runtime::Handle::current(),
        );
    } else {
        tracing::info!("embedding not configured — memory features disabled");
    }

    // Tool registry — load service endpoints from workspace/tools/*.yaml
    let tool_registry = init_tool_registry().await;

    // Container Manager (Docker lifecycle for on-demand MCP servers)
    let container_manager = init_container_manager().await;

    // MCP registry (MCP tool discovery from MCP containers)
    let mcp_registry = init_mcp_registry(container_manager.clone()).await;

    // Load agent configs — no default agent created; Setup Wizard handles first agent
    std::fs::create_dir_all("config/agents")?;
    let mut agent_configs = config::load_agent_configs("config/agents")?;
    if agent_configs.is_empty() {
        tracing::info!("no agent configs found — Setup Wizard will create the first agent");
    }
    tracing::info!(agents = agent_configs.len(), "agent configs loaded");

    // Migrate legacy providers → named connections (one-time, idempotent)
    crate::agent::providers::migrate_legacy_providers(&db_pool, &mut agent_configs).await;

    // Auto-detect FTS language from first agent's language (if not explicitly configured)
    if cfg.memory.fts_language.is_none()
        && let Some(first) = agent_configs.first() {
            let detected = memory::MemoryAdmin::detect_fts_language(&first.agent.language);
            tracing::info!(
                agent = %first.agent.name,
                agent_lang = %first.agent.language,
                fts_lang = %detected,
                "auto-detected FTS language from first agent"
            );
            memory_store.set_fts_language(&detected);
        }

    // UI event broadcast channel (shared between scheduler and WS handler)
    let (ui_event_tx, _) = tokio::sync::broadcast::channel::<String>(512);

    // Scheduler
    let sched = Arc::new(scheduler::Scheduler::new(ui_event_tx.clone()).await?);

    // Extract shared URLs from service configs
    let service_map = tools::service_registry::load_service_map(config::WORKSPACE_DIR).await;
    let toolgate_url = cfg.toolgate_url.clone()
        .or_else(|| service_map.get("toolgate").map(|t| t.url.clone()));

    // Code execution sandbox (optional — requires Docker + sandbox.enabled = true)
    let tool_embed_cache = Arc::new(tools::embedding::ToolEmbeddingCache::new());

    let docker_url = std::env::var("DOCKER_HOST")
        .unwrap_or_else(|_| "tcp://127.0.0.1:2375".to_string());

    let sandbox = if cfg.sandbox.enabled {
        match containers::sandbox::CodeSandbox::new(&docker_url, &cfg.sandbox) {
            Ok(s) => {
                tracing::info!(
                    image = %cfg.sandbox.image,
                    timeout = cfg.sandbox.timeout_secs,
                    "code execution sandbox initialized"
                );
                Some(Arc::new(s))
            }
            Err(e) => {
                tracing::warn!(error = %e, "failed to initialize sandbox, code_exec disabled");
                None
            }
        }
    } else {
        tracing::info!("sandbox disabled (sandbox.enabled = false)");
        None
    };

    // Shared agent dependencies (for hot-starting agents from API)
    let penalty_cache = Arc::new(crate::db::tool_quality::PenaltyCache::new(db_pool.clone()));

    let audit_queue = Arc::new(crate::db::audit_queue::AuditQueue::new(db_pool.clone()));

    let agent_deps = Arc::new(tokio::sync::RwLock::new(gateway::AgentDeps {
        mcp: mcp_registry.clone(),
        workspace_dir: config::WORKSPACE_DIR.to_string(),
        toolgate_url,
        sandbox: sandbox.clone(),
        tool_embed_cache,
        penalty_cache: penalty_cache.clone(),
        audit_queue,
    }));

    // Build running agent handles + access guards
    let agents_map: gateway::AgentMap = Arc::new(tokio::sync::RwLock::new(HashMap::new()));
    let guards_map: gateway::AccessGuardMap = Arc::new(tokio::sync::RwLock::new(HashMap::new()));

    // Stream registry for SSE resume support
    let stream_registry = Arc::new(gateway::stream_registry::StreamRegistry::new(db_pool.clone()));

    // Managed process manager (channels, toolgate — native child processes)
    let base_dir = std::env::current_dir().unwrap_or_else(|_| std::path::PathBuf::from("."));
    let process_manager: Option<Arc<process_manager::ProcessManager>> = if cfg.managed_process.is_empty() {
        None
    } else {
        let pm = Arc::new(process_manager::ProcessManager::new(cfg.managed_process.clone(), base_dir));
        tracing::info!(count = cfg.managed_process.len(), "managed process manager initialized");
        Some(pm)
    };

    // OAuth manager
    let public_url = cfg.gateway.public_url.clone().unwrap_or_else(|| {
        // Extract port from listen address (e.g. "0.0.0.0:18789" → 18789)
        let port = cfg.gateway.listen.rsplit(':').next().unwrap_or("18789");
        format!("http://localhost:{port}")
    });
    let oauth_manager = Arc::new(crate::oauth::OAuthManager::new(
        db_pool.clone(),
        secrets_manager.clone(),
        reqwest::Client::new(),
        public_url,
    ));

    // Shared application state for gateway (built early so start_agent_from_config can use it)
    let state = gateway::AppState {
        agents: gateway::clusters::AgentCore::new(
            agents_map.clone(),
            agent_deps,
            Arc::new(tokio::sync::RwLock::new(std::collections::HashMap::new())),
            tool_registry.clone(),
            sched.clone(),
        ),
        auth: gateway::clusters::AuthServices::new(
            secrets_manager.clone(),
            guards_map.clone(),
            oauth_manager,
            Arc::new(tokio::sync::Mutex::new(std::collections::HashMap::new())),
        ),
        infra: gateway::clusters::InfraServices::new(
            db_pool.clone(),
            memory_store,
            embedder.clone(),
            container_manager.clone(),
            sandbox.clone(),
            process_manager.clone(),
        ),
        channels: gateway::clusters::ChannelBus::new(
            Arc::new(tokio::sync::RwLock::new(Vec::new())),
            log_tx.clone(),
            ui_event_tx.clone(),
            stream_registry.clone(),
        ),
        config: gateway::clusters::ConfigServices::new(
            cfg.clone(),
            shared_config.clone(),
            Arc::new(tokio::sync::Mutex::new(())),
            config_api_write_flag.clone(),
        ),
        status: gateway::clusters::StatusMonitor::new(
            Arc::new(std::sync::RwLock::new(std::collections::HashMap::new())),
            Arc::new(crate::gateway::state::PollingDiagnostics::new()),
            Arc::new(tokio::sync::RwLock::new(None)),
            std::time::Instant::now(),
        ),
    };

    // Managed processes started after TcpListener::bind below — toolgate needs Core API ready.

    // Spawn periodic background tasks (cleanup, watchdog, etc.)
    spawn_background_tasks(&state, process_manager.clone(), &agent_configs).await;

    // Start all agents from config
    start_configured_agents(&state, &agent_configs).await;

    // Load dynamic cron jobs and schedule periodic system jobs
    schedule_periodic_jobs(&state, &agent_configs).await;

    // Background task: renew expiring Gmail watches every 6 hours
    {
        let renewal_db = db_pool.clone();
        let renewal_oauth = state.auth.oauth.clone();
        tokio::spawn(async move {
            let mut interval = tokio::time::interval(std::time::Duration::from_secs(6 * 3600));
            loop {
                interval.tick().await;
                crate::gateway::renew_expiring_gmail_watches(&renewal_db, &renewal_oauth).await;
            }
        });
    }

    // Start gateway (blocks until shutdown signal)
    let listener = tokio::net::TcpListener::bind(&cfg.gateway.listen).await?;
    tracing::info!(addr = %cfg.gateway.listen, "gateway listening");

    // ── mDNS: advertise _hydeclaw._tcp.local. ──
    let _mdns_daemon = setup_mdns(&cfg);

    // Tailscale Funnel setup
    setup_tailscale(&cfg).await;

    // Notify systemd: service is ready (no-op on non-Linux)
    #[cfg(target_os = "linux")]
    setup_linux_service_notify();

    // SIGHUP: hot-restart agents (Unix only)
    #[cfg(unix)]
    setup_sighup_handler(state.clone());

    // Start managed child processes just before serve
    if let Some(ref pm) = process_manager {
        let pm_clone = pm.clone();
        tokio::spawn(async move {
            tokio::time::sleep(std::time::Duration::from_millis(500)).await;
            pm_clone.start_all().await;
        });
    }

    axum::serve(listener, gateway::router(state)?.into_make_service_with_connect_info::<std::net::SocketAddr>())
        .with_graceful_shutdown(shutdown_signal())
        .await?;

    // ── Graceful shutdown: cancel → drain → stop ──────────────────────────
    tracing::info!("graceful shutdown: cancelling all active requests");
    {
        let agents = agents_map.read().await;
        for (name, handle) in agents.iter() {
            tracing::info!(agent = %name, "cancelling active requests");
            handle.engine.state.cancel_all_requests();
        }
    }

    tracing::info!("graceful shutdown: waiting for agents to drain (10s)");
    {
        let agents = agents_map.read().await;
        let drain_futures: Vec<_> = agents.values()
            .map(|h| h.engine.state.wait_drain(std::time::Duration::from_secs(10)))
            .collect();
        futures_util::future::join_all(drain_futures).await;
    }

    tracing::info!("graceful shutdown: stopping agents");
    {
        let mut agents = agents_map.write().await;
        for (name, handle) in agents.drain() {
            tracing::info!(agent = %name, "shutting down agent");
            handle.shutdown(&sched).await;
        }
    }

    tracing::info!("graceful shutdown: stopping managed processes");
    if let Some(pm) = &process_manager { pm.stop_all().await; }

    #[cfg(target_os = "linux")]
    let _ = sd_notify::notify(false, &[sd_notify::NotifyState::Stopping]);

    #[cfg(feature = "otel")]
    if cfg.otel.enabled { opentelemetry::global::shutdown_tracer_provider(); }

    tracing::info!("HydeClaw Core shutting down");
    Ok(())
}

/// Auto-install systemd user units for watchdog and memory-worker if binaries exist.
fn setup_systemd_units() {
    let watchdog_binary = std::path::Path::new("hydeclaw-watchdog");
    if watchdog_binary.exists() {
        let home = std::env::var("HOME")
            .or_else(|_| std::env::var("USERPROFILE"))
            .unwrap_or_else(|_| "/root".into());
        let unit_path = std::path::PathBuf::from(&home)
            .join(".config/systemd/user/hydeclaw-watchdog.service");
        if !unit_path.exists() {
            let cwd = std::env::current_dir().unwrap_or_default();
            let binary_path = cwd.join("hydeclaw-watchdog");
            let auth_token = std::env::var("HYDECLAW_AUTH_TOKEN").unwrap_or_default();
            let unit_content = format!(
                "[Unit]\nDescription=HydeClaw Watchdog\nAfter=network.target\n\n\
                 [Service]\nType=notify\nWorkingDirectory={cwd}\n\
                 ExecStart={binary} config/watchdog.toml\n\
                 Environment=HYDECLAW_AUTH_TOKEN={token}\n\
                 Environment=RUST_LOG=hydeclaw_watchdog=info\n\
                 WatchdogSec=120\nRestart=always\nRestartSec=5\n\n\
                 [Install]\nWantedBy=default.target\n",
                cwd = cwd.display(),
                binary = binary_path.display(),
                token = auth_token,
            );
            if let Some(parent) = unit_path.parent() {
                std::fs::create_dir_all(parent).ok();
            }
            if std::fs::write(&unit_path, &unit_content).is_ok() {
                tracing::info!("watchdog systemd unit installed at {}", unit_path.display());
                let _ = std::process::Command::new("systemctl").args(["--user", "daemon-reload"]).status();
                let _ = std::process::Command::new("systemctl").args(["--user", "enable", "hydeclaw-watchdog"]).status();
                let _ = std::process::Command::new("systemctl").args(["--user", "start", "hydeclaw-watchdog"]).status();
                tracing::info!("watchdog service enabled and started");
            }
        }
    }

    let worker_binary = std::path::Path::new("hydeclaw-memory-worker");
    if worker_binary.exists() {
        let home = std::env::var("HOME")
            .or_else(|_| std::env::var("USERPROFILE"))
            .unwrap_or_else(|_| "/root".into());
        let unit_path = std::path::PathBuf::from(&home)
            .join(".config/systemd/user/hydeclaw-memory-worker.service");
        if !unit_path.exists() {
            let cwd = std::env::current_dir().unwrap_or_default();
            let binary_path = cwd.join("hydeclaw-memory-worker");
            let unit_content = format!(
                "[Unit]\nDescription=HydeClaw Memory Worker\nAfter=network.target\n\n\
                 [Service]\nType=notify\nWorkingDirectory={cwd}\n\
                 ExecStart={binary} config/hydeclaw.toml\n\
                 EnvironmentFile={cwd}/.env\n\
                 Environment=RUST_LOG=hydeclaw_memory_worker=info\n\
                 WatchdogSec=300\nRestart=always\nRestartSec=5\n\n\
                 [Install]\nWantedBy=default.target\n",
                cwd = cwd.display(),
                binary = binary_path.display(),
            );
            if let Some(parent) = unit_path.parent() {
                std::fs::create_dir_all(parent).ok();
            }
            if std::fs::write(&unit_path, &unit_content).is_ok() {
                tracing::info!("memory-worker systemd unit installed at {}", unit_path.display());
                let _ = std::process::Command::new("systemctl").args(["--user", "daemon-reload"]).status();
                let _ = std::process::Command::new("systemctl").args(["--user", "enable", "hydeclaw-memory-worker"]).status();
                let _ = std::process::Command::new("systemctl").args(["--user", "start", "hydeclaw-memory-worker"]).status();
                tracing::info!("memory-worker service enabled and started");
            }
        }
    }
}

/// Repair sessions interrupted by previous crash (batched loop).
async fn cleanup_interrupted_sessions(db_pool: &sqlx::PgPool) {
    loop {
        match crate::db::sessions::cleanup_interrupted_sessions(db_pool).await {
            Ok(0) => {
                tracing::info!("startup cleanup: no more interrupted sessions");
                break;
            }
            Ok(cleaned) => {
                tracing::info!(cleaned, "cleanup batch completed, checking for more");
            }
            Err(e) => {
                tracing::error!(error = %e, "startup cleanup failed (non-fatal)");
                break;
            }
        }
    }
}

/// Load HYDECLAW_MASTER_KEY from environment or auto-generate and save to .env.
fn get_master_key() -> String {
    std::env::var("HYDECLAW_MASTER_KEY").unwrap_or_else(|_| {
        let mut key = [0u8; 32];
        rand::RngCore::fill_bytes(&mut rand::rng(), &mut key);
        let generated = hex::encode(key);
        
        // Try to append to .env automatically
        let env_path = std::path::PathBuf::from(".env");
        if let Ok(mut content) = std::fs::read_to_string(&env_path)
            && !content.contains("HYDECLAW_MASTER_KEY") {
                if !content.ends_with('\n') { content.push('\n'); }
                content.push_str(&format!("HYDECLAW_MASTER_KEY={generated}\n"));
                if std::fs::write(&env_path, content).is_ok() {
                    eprintln!("[dotenv] HYDECLAW_MASTER_KEY auto-generated and saved to .env");
                }
            }

        eprintln!();
        eprintln!("!!! HYDECLAW_MASTER_KEY is not set !!!");
        eprintln!("Secrets encrypted this session will be LOST on restart.");
        eprintln!("Add this to your .env file and restart:");
        eprintln!("  HYDECLAW_MASTER_KEY={generated}");
        eprintln!();
        tracing::error!(
            "HYDECLAW_MASTER_KEY not set — ephemeral key in use, secrets will NOT survive restart"
        );
        generated
    })
}

/// Initialize the tool registry by loading service endpoints from the workspace.
async fn init_tool_registry() -> tools::ToolRegistry {
    let service_map = tools::service_registry::load_service_map(config::WORKSPACE_DIR).await;
    let tool_registry = tools::ToolRegistry::from_config(&service_map);
    tracing::info!(tools = tool_registry.len().await, "tool registry loaded from workspace");

    // Spawn periodic health check for external tools
    let registry = tool_registry.clone();
    tokio::spawn(async move {
        let mut interval = tokio::time::interval(std::time::Duration::from_secs(60));
        loop {
            interval.tick().await;
            registry.health_check().await;
        }
    });

    // Periodic upload cleanup (every hour, delete files older than 7 days)
    tokio::spawn(async move {
        let mut interval = tokio::time::interval(std::time::Duration::from_secs(3600));
        loop {
            interval.tick().await;
            agent::cleanup_stale_uploads(
                config::WORKSPACE_DIR,
                std::time::Duration::from_secs(7 * 86400),
            ).await;
        }
    });

    tool_registry
}

/// Initialize the Container Manager for Docker-based MCP servers.
async fn init_container_manager() -> Option<Arc<containers::ContainerManager>> {
    let docker_url = std::env::var("DOCKER_HOST")
        .unwrap_or_else(|_| "tcp://127.0.0.1:2375".to_string());
    let mcp_map = crate::tools::mcp_workspace::load_mcp_map(crate::config::MCP_DIR).await;
    tracing::info!(count = mcp_map.len(), dir = crate::config::MCP_DIR, "loaded MCP configs from workspace");

    match containers::ContainerManager::new(&docker_url, mcp_map.clone()) {
        Ok(cm) => {
            let cm = Arc::new(cm);
            // Start persistent MCP servers
            if let Err(e) = cm.start_persistent().await {
                tracing::warn!(error = %e, "failed to start some persistent MCP MCP servers");
            }
            // Cleanup orphaned on-demand containers from previous crash
            cm.cleanup_orphans().await;
            // Spawn idle reaper
            let cm_clone = cm.clone();
            tokio::spawn(async move {
                let mut interval = tokio::time::interval(std::time::Duration::from_secs(30));
                loop {
                    interval.tick().await;
                    cm_clone.reap_idle().await;
                }
            });
            Some(cm)
        }
        Err(e) => {
            tracing::warn!(error = %e, "Docker not available, MCP disabled");
            None
        }
    }
}

/// Initialize the MCP registry and discover tools from persistent servers.
async fn init_mcp_registry(container_manager: Option<Arc<containers::ContainerManager>>) -> Option<Arc<mcp::McpRegistry>> {
    let mcp_map = crate::tools::mcp_workspace::load_mcp_map(crate::config::MCP_DIR).await;
    let mcp_registry = container_manager.map(|cm| {
        let sr = mcp::McpRegistry::new(cm);
        Arc::new(sr)
    });

    // Discover tools from persistent MCP servers
    if let Some(ref sr) = mcp_registry {
        for (name, entry) in &mcp_map {
            if entry.mode == "persistent" {
                match sr.discover_tools(name).await {
                    Ok(tools) => {
                        tracing::info!(mcp = %name, tools = tools.len(), "discovered MCP tools");
                    }
                    Err(e) => {
                        tracing::warn!(mcp = %name, error = %e, "failed to discover MCP tools");
                    }
                }
            }
        }
    }
    mcp_registry
}

/// Spawn various background tasks for session cleanup, watchdog, and health monitoring.
async fn spawn_background_tasks(
    state: &gateway::AppState,
    process_manager: Option<Arc<process_manager::ProcessManager>>,
    agent_configs: &[config::AgentConfig],
) {
    // Periodic session agent pool cleanup (every 5 minutes)
    let pools = state.agents.session_pools.clone();
    tokio::spawn(async move {
        let mut interval = tokio::time::interval(std::time::Duration::from_secs(300));
        loop {
            interval.tick().await;
            agent::session_agent_pool::cleanup_stale_pools(&pools).await;
        }
    });

    // Stream cleanup: in-memory broadcast (2 min TTL) + DB jobs (1 hour TTL)
    let registry = state.channels.stream_registry.clone();
    let cleanup_db = state.infra.db.clone();
    tokio::spawn(async move {
        let mut interval = tokio::time::interval(std::time::Duration::from_secs(300));
        loop {
            interval.tick().await;
            registry.cleanup(std::time::Duration::from_secs(120)).await;
            gateway::stream_jobs::cleanup_old_jobs(&cleanup_db).await.ok();
        }
    });

    // Watchdog: detect and kill sessions stuck in 'running'
    let watchdog_db = state.infra.db.clone();
    let watchdog_registry = state.channels.stream_registry.clone();
    let inactivity_secs = agent_configs
        .iter()
        .filter_map(|c| c.agent.watchdog.as_ref())
        .map(|w| w.inactivity_secs)
        .min()
        .unwrap_or(600);
    tokio::spawn(async move {
        let mut interval = tokio::time::interval(std::time::Duration::from_secs(60));
        loop {
            interval.tick().await;
            match crate::db::sessions::find_stale_running_sessions(&watchdog_db, inactivity_secs).await {
                Ok(stale) if stale.is_empty() => {}
                Ok(stale) => {
                    tracing::warn!(count = stale.len(), "watchdog: found {} stale running session(s)", stale.len());
                    for (session_id, agent_id) in stale {
                        tracing::warn!(%session_id, %agent_id, "watchdog: killing stale session");
                        watchdog_registry.cancel(&session_id.to_string()).await;
                        sqlx::query("DELETE FROM messages WHERE session_id = $1 AND status = 'streaming'")
                            .bind(session_id).execute(&watchdog_db).await.ok();
                        crate::db::sessions::insert_synthetic_tool_results(&watchdog_db, session_id).await.ok();
                        crate::db::sessions::set_session_run_status(&watchdog_db, session_id, "timeout").await.ok();
                    }
                }
                Err(e) => tracing::error!(error = %e, "watchdog query failed"),
            }
        }
    });

    // Channel health monitor
    let health_channels = state.channels.connected_channels.clone();
    let health_pm = process_manager;
    tokio::spawn(async move {
        let mut interval = tokio::time::interval(std::time::Duration::from_secs(120));
        loop {
            interval.tick().await;
            let now = chrono::Utc::now();
            let stale_threshold = chrono::Duration::minutes(5);
            let channels = health_channels.read().await;
            let mut needs_restart = false;
            for ch in channels.iter() {
                if now - ch.last_activity > stale_threshold {
                    tracing::warn!(agent = %ch.agent_name, channel = %ch.channel_type, "stale channel adapter detected");
                    needs_restart = true;
                }
            }
            drop(channels);
            if needs_restart && let Some(ref pm) = health_pm {
                pm.restart("channels").await.ok();
            }
        }
    });
}

/// Start all agents defined in the configuration.
async fn start_configured_agents(state: &gateway::AppState, agent_configs: &[config::AgentConfig]) {
    for agent_cfg in agent_configs {
        match gateway::start_agent_from_config(
            agent_cfg,
            &state.agents,
            &state.infra,
            &state.auth,
            &state.channels,
            &state.config,
            &state.status,
        ).await {
            Ok((handle, guard)) => {
                let name = agent_cfg.agent.name.clone();
                state.agents.map.write().await.insert(name.clone(), handle);
                if let Some(guard) = guard {
                    state.auth.access_guards.write().await.insert(name.clone(), guard);
                }
                // Ensure sandbox
                if !agent_cfg.agent.base && let Some(ref sb) = state.infra.sandbox {
                    let deps = state.agents.deps.read().await;
                    if let Ok(host_path) = std::fs::canonicalize(&deps.workspace_dir) {
                        sb.ensure_container(&name, &host_path.to_string_lossy(), false, Some(&state.auth.oauth)).await.ok();
                    }
                }
            }
            Err(e) => tracing::error!(agent = %agent_cfg.agent.name, error = %e, "failed to start agent"),
        }
    }
}

/// Schedule periodic system maintenance jobs (decay, cleanup, backup).
async fn schedule_periodic_jobs(state: &gateway::AppState, agent_configs: &[config::AgentConfig]) {
    let sched = &state.agents.scheduler;
    let db = &state.infra.db;

    // Load dynamic cron jobs
    let engines = state.agents.get_engines_map().await;
    sched.load_dynamic_jobs(db, &engines).await.ok();

    // Daily maintenance jobs
    sched.add_memory_decay(db.clone()).await.ok();
    sched.add_task_cleanup(db.clone()).await.ok();
    sched.add_audit_cleanup(db.clone(), 30).await.ok();
    sched.add_tool_audit_cleanup(db.clone(), 90).await.ok();
    sched.add_pending_messages_cleanup(db.clone()).await.ok();
    sched.add_outbound_queue_cleanup(db.clone()).await.ok();
    sched.add_usage_log_cleanup(db.clone()).await.ok();
    sched.add_memory_decay_cleanup(db.clone()).await.ok();
    sched.add_notifications_cleanup(db.clone()).await.ok();

    // Session cleanup (based on max TTL in agent configs)
    let ttl_days = agent_configs.iter().filter_map(|c| c.agent.session.as_ref()).map(|s| s.ttl_days).max().unwrap_or(30);
    sched.add_session_cleanup(db.clone(), ttl_days).await.ok();

    // Automatic backup
    if state.config.config.backup.enabled {
        sched.add_backup(
            &state.config.config.backup.cron, state.config.config.backup.retention_days,
            db.clone(), state.auth.secrets.clone(), state.agents.deps.clone(),
        ).await.ok();
    }

    sched.start().await.ok();
}

/// Advertise the service via mDNS.
fn setup_mdns(cfg: &config::AppConfig) -> Option<mdns_sd::ServiceDaemon> {
    use mdns_sd::{ServiceDaemon, ServiceInfo};
    let port = cfg.gateway.listen.split(':').next_back().and_then(|p| p.parse().ok()).unwrap_or(18789);
    
    ServiceDaemon::new().ok().and_then(|daemon| {
        let props = [("version", env!("CARGO_PKG_VERSION"))].into_iter().map(|(k, v)| (k.to_string(), v.to_string())).collect();
        ServiceInfo::new("_hydeclaw._tcp.local.", "hydeclaw", "hydeclaw.local.", (), port, Some(props)).ok().and_then(|info| {
            daemon.register(info).ok()?;
            tracing::info!(port, "mDNS registered: hydeclaw._hydeclaw._tcp.local.");
            Some(daemon)
        })
    })
}

/// Setup Tailscale Funnel or Serve.
async fn setup_tailscale(cfg: &config::AppConfig) {
    if cfg.tailscale.enabled {
        let port = cfg.gateway.listen.split(':').next_back().unwrap_or("18789");
        let target = format!("https+insecure://localhost:{port}");
        let cmd = if cfg.tailscale.funnel { "funnel" } else { "serve" };
        tokio::process::Command::new("tailscale").args([cmd, "--bg", &target]).output().await.ok();
    }
}

/// Notify systemd that the service is ready and start watchdog ticker.
#[cfg(target_os = "linux")]
fn setup_linux_service_notify() {
    let _ = sd_notify::notify(false, &[sd_notify::NotifyState::Ready]);
    tokio::spawn(async {
        let mut interval = tokio::time::interval(std::time::Duration::from_secs(60));
        loop {
            interval.tick().await;
            let _ = sd_notify::notify(false, &[sd_notify::NotifyState::Watchdog]);
        }
    });
}

/// Setup SIGHUP handler for hot-reloading agent configs (Unix only).
/// Uses cancel → drain → replace pattern to avoid disrupting in-flight requests.
#[cfg(unix)]
fn setup_sighup_handler(state: gateway::AppState) {
    tokio::spawn(async move {
        use tokio::signal::unix::{signal, SignalKind};
        let mut sighup = signal(SignalKind::hangup()).expect("failed to register SIGHUP");
        loop {
            sighup.recv().await;
            tracing::info!("SIGHUP received — reloading agent configs with graceful drain");
            if let Ok(configs) = crate::config::load_agent_configs("config/agents") {
                for cfg in configs {
                    let name = cfg.agent.name.clone();

                    // 1. Cancel old agent's active requests
                    if let Some(old_handle) = state.agents.map.read().await.get(&name) {
                        tracing::info!(agent = %name, "SIGHUP: cancelling old agent requests");
                        old_handle.engine.state.cancel_all_requests();
                    }

                    // 2. Wait for drain (10s timeout)
                    if let Some(old_handle) = state.agents.map.read().await.get(&name) {
                        tracing::info!(agent = %name, "SIGHUP: waiting for drain");
                        old_handle.engine.state.wait_drain(std::time::Duration::from_secs(10)).await;
                    }

                    // 3. Create new engine and replace
                    if let Ok((handle, guard)) = crate::gateway::start_agent_from_config(
                        &cfg,
                        &state.agents,
                        &state.infra,
                        &state.auth,
                        &state.channels,
                        &state.config,
                        &state.status,
                    ).await {
                        if let Some(old) = state.agents.map.write().await.remove(&name) {
                            old.shutdown(&state.agents.scheduler).await;
                        }
                        state.agents.map.write().await.insert(name.clone(), handle);
                        if let Some(g) = guard {
                            state.auth.access_guards.write().await.insert(name.clone(), g);
                        }
                        tracing::info!(agent = %name, "SIGHUP: agent reloaded");
                    }
                }
            }
        }
    });
}

async fn shutdown_signal() {
    let ctrl_c = async {
        tokio::signal::ctrl_c()
            .await
            .expect("failed to install Ctrl+C handler");
    };

    #[cfg(unix)]
    let terminate = async {
        tokio::signal::unix::signal(tokio::signal::unix::SignalKind::terminate())
            .expect("failed to install SIGTERM handler")
            .recv()
            .await;
    };

    #[cfg(not(unix))]
    let terminate = std::future::pending::<()>();

    tokio::select! {
        () = ctrl_c => tracing::info!("received Ctrl+C"),
        () = terminate => tracing::info!("received SIGTERM"),
    }

    // Safety net: force-exit after 15s if graceful shutdown hangs
    tokio::spawn(async {
        tokio::time::sleep(std::time::Duration::from_secs(15)).await;
        tracing::warn!("hard shutdown: 15s timeout exceeded");
        std::process::exit(1);
    });
}

